- name: Launch a compute instance
  hosts: localhost
  gather_facts: true
  collections:
    - oracle.oci
  tasks:

- name: Include instance details.
  include_vars: ./instance_details.yml

- name: Create bastion ssh session
  oci_bastion_session:
    bastion_id: "{{ bastion_ocid }}"
    target_resource_details:
      target_resource_operating_system_user_name: "opc"
      session_type: MANAGED_SSH
      target_resource_id: "{{ instance_ocid }}"
      target_resource_port: 22
    key_details:
      public_key_content: "{{ SSH_AUTHORIZED_KEYS }}"
    key_type: PUB
    session_ttl_in_seconds: 3600
    display_name: "{{ instance_name }}-bastion-session-ssh"
  register: result
  when:
    - "instancedetails is defined"

- set_fact:
    bastion_session_details: "{{ result }}"
  when:
    - "instancedetails is defined"

- name: Print bastion session connection
  ansible.builtin.debug:
    msg: 'Bastion ssh: ssh -i server.key -o ProxyCommand="ssh -i server.key -W %h:%p -p 22 {{ bastion_session_details.session.bastion_id }}@host.bastion.{{ region }}.oci.oraclecloud.com" -p 22 opc@{{ private_ip }}'
  when:
    - "instancedetails is defined"